name: Pull plugin stats

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pull-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
        run: |
          node update-stats.js
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
      - name: Commit report
        run: |
          git config --global user.name 'Obsidian Bot'
          git config --global user.email 'admin@obsidian.md'
          git commit -am "Update plugin stats"
          git push