name: Pull plugin stats

# on:
#   schedule:
#     - cron: "0 0 * * *"

# run it on closing PR to test the workflow, will remove once it works
on:
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  pull-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: |
          node update-stats.js
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit updates
        run: |
          git config --local user.name 'Obsidian Bot'
          git config --local user.email 'admin@obsidian.md'
          git commit -am "chore: Update plugin stats"
          git push